Repository woowacourse-teams/2021-botobo, pull requests merged in 2021-08, with the labels that each got.

#271 W10 - 문제집 삭제시 가지고 있는 카드도 삭제하는 기능을 추가하고 코드 일부를 리팩터링한다.
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/domain/card/Card.java
  backend/src/main/java/botobo/core/domain/card/Cards.java
  backend/src/main/java/botobo/core/domain/user/User.java
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookUpdateRequest.java
  backend/src/main/java/botobo/core/ui/WorkbookController.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookRepositoryTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookTest.java
Labels: 👩‍💻 백엔드

#290 F19 - 스크롤 탑 고정, 라우터를 정리한다
  frontend/src/Router.tsx
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/PublicWorkbookPage.tsx
  frontend/src/pages/QuizResultPage.tsx
  frontend/src/pages/QuizSettingPage.tsx
Labels: 👨‍💻 프론트엔드, 🛠 리팩터링

#293 F21 - google analytics 적용하기
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/yarn.lock
Labels: 👨‍💻 프론트엔드, 📍 기능

#275 T01 - 문제집 CRUD에 태그 추가
  backend/src/docs/sql/ddl.sql
  backend/src/docs/sql/dml.sql
  backend/src/main/java/botobo/core/DataLoader.java
  backend/src/main/java/botobo/core/application/TagService.java
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/domain/tag/Tag.java
  backend/src/main/java/botobo/core/domain/tag/TagName.java
  backend/src/main/java/botobo/core/domain/tag/TagRepository.java
  backend/src/main/java/botobo/core/domain/tag/Tags.java
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/main/java/botobo/core/domain/workbooktag/WorkbookTag.java
  backend/src/main/java/botobo/core/domain/workbooktag/WorkbookTagRepository.java
  backend/src/main/java/botobo/core/dto/tag/TagRequest.java
  backend/src/main/java/botobo/core/dto/tag/TagResponse.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookRequest.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookResponse.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookUpdateRequest.java
  backend/src/main/java/botobo/core/exception/tag/InvalidTagNameException.java
  backend/src/main/java/botobo/core/exception/tag/TagCreationFailureException.java
  backend/src/main/java/botobo/core/exception/tag/TagNamesCreationFailureException.java
  backend/src/main/java/botobo/core/exception/tag/TagsCreationFailureException.java
  backend/src/main/java/botobo/core/exception/workbook/WorkbookTagLimitException.java
  backend/src/main/java/botobo/core/exception/workbooktag/WorkbookTagCreationFailureException.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/application/TagServiceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
  backend/src/test/java/botobo/core/domain/tag/TagNameTest.java
  backend/src/test/java/botobo/core/domain/tag/TagRepositoryTest.java
  backend/src/test/java/botobo/core/domain/tag/TagTest.java
  backend/src/test/java/botobo/core/domain/tag/TagsTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookRepositoryTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookTest.java
  backend/src/test/java/botobo/core/domain/workbooktag/WorkbookTagTest.java
Labels: 👩‍💻 백엔드

#296 M07 - 문제집 관련 api 수정
  frontend/src/App.tsx
  frontend/src/api/index.ts
  frontend/src/pages/WorkbookEditPage.tsx
  frontend/src/recoil/workbookState.ts
Labels: 🐜 버그, 👨‍💻 프론트엔드

#295 W13 - 공유 문제집 상세보기 api를 구현한다.
  backend/src/docs/asciidoc/workbooks.adoc
  backend/src/docs/request/workbooks.http
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/botobo/core/dto/card/CardResponse.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookCardResponse.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookUpdateRequest.java
  backend/src/main/java/botobo/core/ui/WorkbookController.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
Labels: 👩‍💻 백엔드, 📍 기능

#299 F22 - 전체적인 디자인 리터치
  frontend/src/GlobalStyle.tsx
  frontend/src/api/index.ts
  frontend/src/assets/design-thinking.svg
  frontend/src/components/QnACard.tsx
  frontend/src/components/QuizStarter.tsx
  frontend/src/hooks/useCard.ts
  frontend/src/hooks/usePublicCard.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PublicCardsPage.tsx
Labels: 🐜 버그, 👨‍💻 프론트엔드, 💄UI

#309 F23 - 모달 관련 리팩터링
  frontend/src/components/Category.tsx
  frontend/src/components/CategoryList.tsx
  frontend/src/components/PublicCardsSelectBox.tsx
  frontend/src/components/index.ts
  frontend/src/contexts/FormProvider.tsx
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/hooks/useCards.ts
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/recoil/categoryState.ts
Labels: 👨‍💻 프론트엔드, 🛠 리팩터링

#317 F24 - 소규모 리팩토링
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  frontend/package.json
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/components/QnACard.tsx
  frontend/src/hooks/useCard.ts
  frontend/src/hooks/usePublicCard.ts
  frontend/src/hooks/usePublicWorkbook.ts
  frontend/src/hooks/useQuiz.ts
  frontend/src/hooks/useQuizSetting.ts
  frontend/src/hooks/useWorkbook.ts
  frontend/src/pages/CardsPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicWorkbookPage.tsx
  frontend/src/recoil/cardState.ts
  frontend/src/recoil/index.ts
  frontend/src/recoil/quizState.ts
  frontend/src/recoil/userState.ts
  frontend/src/recoil/workbookState.ts
Labels: 👨‍💻 프론트엔드, 🛠 리팩터링

#319 F25 - 페이지 헤더를 메인 헤더로 바꾼다
  frontend/src/components/MainHeader.tsx
  frontend/src/components/PageHeader.tsx
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/pages/CardsPage.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicWorkbookPage.tsx
  frontend/src/pages/QuizPage.tsx
  frontend/src/pages/QuizResultPage.tsx
  frontend/src/pages/QuizSettingPage.tsx
  frontend/src/pages/WorkbookAddPage.tsx
  frontend/yarn.lock
Labels: 👨‍💻 프론트엔드, 💄UI

#321 F26 - 대규모 리팩토링
  frontend/src/api/index.ts
  frontend/src/components/CardAddForm.tsx
  frontend/src/components/CardEditForm.tsx
  frontend/src/components/CardTextArea.tsx
  frontend/src/components/Checkbox.tsx
  frontend/src/components/Hashtag.tsx
  frontend/src/components/PublicCardsSelectBox.tsx
  frontend/src/components/SelectBox.tsx
  frontend/src/hooks/useQuiz.ts
  frontend/src/hooks/useWorkbook.ts
  frontend/src/pages/CardsPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicWorkbookPage.tsx
  frontend/src/pages/WorkbookEditPage.tsx
Labels: 👨‍💻 프론트엔드, 🛠 리팩터링

#303 C10 - 또 보기 카드 등록 관련 테스트 리팩토링을 한다.
  backend/src/docs/asciidoc/categories.adoc
  backend/src/docs/asciidoc/quizzes.adoc
  backend/src/docs/request/quizzes.http
  backend/src/main/resources/import.sql
  backend/src/test/java/botobo/core/acceptance/card/QuizAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/application/QuizServiceTest.java
  backend/src/test/java/botobo/core/documentation/AdminDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/QuizDocumentationTest.java
  backend/src/test/java/botobo/core/domain/card/CardRepositoryTest.java
  backend/src/test/java/botobo/core/utils/Fixture.java
Labels: 👩‍💻 백엔드

#307 W11, W12, W14 - 자신의 문제집만 카드 모아보기 추가 및 문제집 인수테스트 리팩터링
  backend/src/docs/asciidoc/workbooks.adoc
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/ui/WorkbookController.java
  backend/src/test/java/botobo/core/acceptance/DomainAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
Labels: 👩‍💻 백엔드

#310 B38 - RequestBuilder 리팩토링
  backend/src/test/java/botobo/core/AcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/AcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/card/CardAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/card/QuizAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/utils/RequestBuilder.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/documentation/DocumentationUtils.java
  backend/src/test/java/botobo/core/documentation/utils/DocumentationUtils.java
Labels: 👩‍💻 백엔드

#324 P04 - 문제집 가져가기 리팩토링을 한다
  frontend/src/components/PublicCardsSelectBox.tsx
Labels: 👨‍💻 프론트엔드, 🛠 리팩터링

#322 B41 - 경로와 HttpMethod를 이용해 인터셉터 설정 가능하도록 수정 및 /api/workbooks 경로를 인터셉터에 추가한다.
  backend/src/main/java/botobo/core/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/botobo/core/ui/auth/AdminInterceptor.java
  backend/src/main/java/botobo/core/ui/auth/AuthorizationInterceptor.java
  backend/src/main/java/botobo/core/ui/auth/PathMatcherInterceptor.java
  backend/src/main/java/botobo/core/ui/auth/PathMethod.java
  backend/src/main/java/botobo/core/ui/auth/PathMethods.java
  backend/src/main/java/botobo/core/ui/auth/PathPatterns.java
  backend/src/test/java/botobo/core/domain/auth/PathMatcherInterceptorTest.java
  backend/src/test/java/botobo/core/domain/auth/PathMethodsTest.java
  backend/src/test/java/botobo/core/domain/auth/PathPatternsTest.java
Labels: 👩‍💻 백엔드

#326 Q16 - 퀴즈 페이지의 카드 슬라이드를 구현한다
  frontend/src/pages/QuizPage.tsx
Labels: 👨‍💻 프론트엔드, 📍 기능, 💄UI

#330 M08 - 메인 헤더의 메뉴를 구현한다
  frontend/src/Router.tsx
  frontend/src/assets/logout.svg
  frontend/src/assets/menu.svg
  frontend/src/components/MainHeader.tsx
  frontend/src/constants/route.ts
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/LogoutPage.tsx
  frontend/src/pages/index.ts
Labels: 👨‍💻 프론트엔드, 💄UI

#333 U10 - 유저의 마이 페이지를 구현한다
  frontend/src/Router.tsx
  frontend/src/assets/pencil.svg
  frontend/src/components/CardTextArea.tsx
  frontend/src/components/MainHeader.tsx
  frontend/src/components/TextAreaField.tsx
  frontend/src/components/index.ts
  frontend/src/constants/index.ts
  frontend/src/constants/route.ts
  frontend/src/contexts/FormProvider.tsx
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/index.ts
Labels: 👨‍💻 프론트엔드

#334 S02 - 검색 페이지 UI 및 기능을 구현한다
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/assets/business-card.svg
  frontend/src/assets/tag.svg
  frontend/src/components/MainHeader.tsx
  frontend/src/components/PublicSearchList.tsx
  frontend/src/components/PublicWorkbookList.tsx
  frontend/src/components/index.ts
  frontend/src/constants/index.ts
  frontend/src/constants/route.ts
  frontend/src/constants/search.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/usePublicSearch.ts
  frontend/src/hooks/usePublicSearchQuery.ts
  frontend/src/hooks/usePublicWorkbook.ts
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/PublicSearchResultLoadable.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
  frontend/src/pages/PublicWorkbookPage.tsx
  frontend/src/pages/index.ts
  frontend/src/recoil/index.ts
  frontend/src/recoil/workbookState.ts
  frontend/src/types/index.ts
  frontend/src/types/utils.ts
Labels: 👨‍💻 프론트엔드

#340 C11 - 카드 상세 페이지에 하트 기능을 추가한다
  frontend/src/api/index.ts
  frontend/src/assets/heart-regular.svg
  frontend/src/assets/heart-solid.svg
  frontend/src/hooks/usePublicCard.ts
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/types/index.ts
Labels: 👨‍💻 프론트엔드

#348 Q17 - 카드 슬라이드 메시지가 모바일에서만 보이도록 수정한다
  frontend/src/hooks/useQuiz.ts
  frontend/src/pages/QuizPage.tsx
Labels: 👨‍💻 프론트엔드

#352 F28 - 카드의 개행이 되지 않는 문제를 해결한다
  frontend/src/components/CardTemplate.tsx
Labels: 👨‍💻 프론트엔드

#354 U11 - 마이페이지의 정보를 수정한다
  frontend/src/__tests__/MainPage.test.tsx
  frontend/src/api/index.ts
  frontend/src/components/TextAreaField.tsx
  frontend/src/contexts/FormProvider.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useProfile.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/types/index.ts
Labels: 👨‍💻 프론트엔드

#343 U11 - 마이페이지 프로필 닉네임 및 바이오 수정 api 구현, U12 - 회원명 중복 검사 api를 구현한다.
  backend/src/docs/asciidoc/user.adoc
  backend/src/docs/request/users.http
  backend/src/main/java/botobo/core/application/AbstractUserService.java
  backend/src/main/java/botobo/core/application/UserService.java
  backend/src/main/java/botobo/core/domain/user/User.java
  backend/src/main/java/botobo/core/domain/user/UserRepository.java
  backend/src/main/java/botobo/core/dto/user/ProfileResponse.java
  backend/src/main/java/botobo/core/dto/user/UserNameRequest.java
  backend/src/main/java/botobo/core/dto/user/UserNameValidator.java
  backend/src/main/java/botobo/core/dto/user/UserResponse.java
  backend/src/main/java/botobo/core/dto/user/UserUpdateRequest.java
  backend/src/main/java/botobo/core/dto/user/ValidUserName.java
  backend/src/main/java/botobo/core/exception/GlobalControllerAdvice.java
  backend/src/main/java/botobo/core/exception/common/ConflictException.java
  backend/src/main/java/botobo/core/exception/user/ProfileUpdateNotAllowedException.java
  backend/src/main/java/botobo/core/exception/user/UserNameDuplicatedException.java
  backend/src/main/java/botobo/core/ui/UserController.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/botobo/core/acceptance/user/UserAcceptanceTest.java
  backend/src/test/java/botobo/core/application/UserServiceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/UserDocumentationTest.java
  backend/src/test/java/botobo/core/domain/user/UserRepositoryTest.java
  backend/src/test/java/botobo/core/domain/user/UserTest.java
Labels: 👩‍💻 백엔드

#362 B45 - 소나큐브를 CI 과정에 도입한다
  backend/build.gradle
  backend/src/main/java/botobo/core/config/WebConfig.java
Labels: 👩‍💻 백엔드

#364 B45 - 소나큐브를 CI 과정에 도입한다 - 2
  backend/build.gradle
Labels: 👩‍💻 백엔드

#356 Q18 - 퀴즈 설정 페이지 UI 및 기능을 구현한다
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/components/SelectBox.tsx
  frontend/src/components/Timer.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useInterval.ts
  frontend/src/hooks/useQuiz.ts
  frontend/src/hooks/useQuizResult.ts
  frontend/src/hooks/useQuizSetting.ts
  frontend/src/pages/PublicCardsLoadable.tsx
  frontend/src/pages/QuizPage.tsx
  frontend/src/pages/QuizResultPage.tsx
  frontend/src/pages/QuizSettingLoadable.tsx
  frontend/src/pages/QuizSettingPage.tsx
  frontend/src/pages/index.ts
  frontend/src/recoil/index.ts
  frontend/src/recoil/quizState.ts
  frontend/src/utils/index.ts
  frontend/src/utils/time.ts
Labels: 👨‍💻 프론트엔드

#350 F27 - 마주친 횟수를 표시한다(퀴즈 페이지 및 카드 모아보기 페이지)
  frontend/src/components/QnACard.tsx
  frontend/src/components/Quiz.tsx
  frontend/src/components/QuizResult.tsx
  frontend/src/pages/QuizPage.tsx
  frontend/src/pages/QuizResultPage.tsx
Labels: 👨‍💻 프론트엔드

#363 U13 - 유저 정보 수정 필드에서 id를 제거한다
  frontend/src/api/index.ts
  frontend/src/hooks/useProfile.ts
  frontend/src/pages/ProfilePage.tsx
Labels: 👨‍💻 프론트엔드

#359 U12 - 구글 소셜 로그인을 구현한다
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/assets/google-logo.svg
  frontend/src/components/OAuth.tsx
  frontend/src/constants/route.ts
  frontend/src/constants/storage.ts
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/OAuthCallbackPage.tsx
  frontend/src/pages/index.ts
  frontend/src/types/index.ts
Labels: 👨‍💻 프론트엔드

#366 M09 - 문제집 추가 페이지에서 발생하는 메인 헤더 z-index 오류를 수정한다
  frontend/src/components/MainHeader.tsx
  frontend/src/pages/WorkbookAddPage.tsx
Labels: 👨‍💻 프론트엔드

#368 F29 - 웹팩 번들 사이즈를 줄인다
  frontend/babel.config.js
  frontend/package.json
  frontend/public/index.html
  frontend/src/GlobalStyle.tsx
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: 👨‍💻 프론트엔드

#341 S01 - 태그, 작성자 기준으로 검색 가능하도록 세분화한다.
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/search.adoc
  backend/src/docs/asciidoc/workbooks.adoc
  backend/src/docs/dummydata/database.txt
  backend/src/docs/dummydata/java.txt
  backend/src/docs/dummydata/network.txt
  backend/src/docs/dummydata/react.txt
  backend/src/docs/dummydata/spring.txt
  backend/src/docs/request/search.http
  backend/src/main/java/botobo/core/DataLoader.java
  backend/src/main/java/botobo/core/application/SearchService.java
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/config/ApplicationConfig.java
  backend/src/main/java/botobo/core/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/botobo/core/domain/tag/TagRepository.java
  backend/src/main/java/botobo/core/domain/user/UserRepository.java
  backend/src/main/java/botobo/core/domain/workbook/WorkbookFinder.java
  backend/src/main/java/botobo/core/domain/workbook/WorkbookRepository.java
  backend/src/main/java/botobo/core/domain/workbook/criteria/AccessType.java
  backend/src/main/java/botobo/core/domain/workbook/criteria/WorkbookCriteria.java
  backend/src/main/java/botobo/core/dto/user/SimpleUserResponse.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookRequest.java
  backend/src/main/java/botobo/core/exception/GlobalControllerAdvice.java
  backend/src/main/java/botobo/core/exception/search/InvalidPageableException.java
  backend/src/main/java/botobo/core/exception/search/InvalidSearchCriteriaException.java
  backend/src/main/java/botobo/core/exception/search/InvalidSearchOrderException.java
  backend/src/main/java/botobo/core/exception/search/InvalidSearchTypeException.java
  backend/src/main/java/botobo/core/exception/search/SearchKeywordCreationFailureException.java
  backend/src/main/java/botobo/core/exception/tag/TagNamesCreationFailureException.java
  backend/src/main/java/botobo/core/ui/WorkbookController.java
  backend/src/main/java/botobo/core/ui/search/SearchArgumentResolver.java
  backend/src/main/java/botobo/core/ui/search/SearchController.java
  backend/src/main/java/botobo/core/ui/search/SearchCriteria.java
  backend/src/main/java/botobo/core/ui/search/SearchKeyword.java
  backend/src/main/java/botobo/core/ui/search/SearchOrder.java
  backend/src/main/java/botobo/core/ui/search/SearchParams.java
  backend/src/main/java/botobo/core/ui/search/SearchType.java
  backend/src/main/java/botobo/core/ui/search/WorkbookSearchParameter.java
  backend/src/test/java/botobo/core/acceptance/AcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/DomainAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/search/SearchAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/utils/RequestBuilder.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/application/SearchServiceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/SearchDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookFinderTest.java
  backend/src/test/java/botobo/core/domain/workbook/criteria/AccessTypeTest.java
  backend/src/test/java/botobo/core/domain/workbook/criteria/WorkbookCriteriaTest.java
  backend/src/test/java/botobo/core/ui/search/SearchCriteriaTest.java
  backend/src/test/java/botobo/core/ui/search/SearchKeywordTest.java
  backend/src/test/java/botobo/core/ui/search/SearchOrderTest.java
  backend/src/test/java/botobo/core/ui/search/SearchTypeTest.java
  backend/src/test/java/botobo/core/ui/search/WorkbookSearchParameterTest.java
  backend/src/test/java/botobo/core/utils/DummyRequestBuilder.java
Labels: 👩‍💻 백엔드

#370 U14 - 유저 이름 중복 조회 오류를 수정한다
  frontend/src/api/index.ts
  frontend/src/contexts/FormProvider.tsx
  frontend/src/hooks/useProfile.ts
  frontend/src/pages/ProfilePage.tsx
Labels: 👨‍💻 프론트엔드

#373 C12 - 공유 카드 페이지의 하트 기능의 오작동을 수정한다
  frontend/src/api/index.ts
  frontend/src/hooks/usePublicCard.ts
Labels: 👨‍💻 프론트엔드

#375 F30 - 메인 헤더와 페이지 헤더가 같이 있을 경우 그림자를 모두 해제한다
  frontend/src/pages/PublicCardsPage.tsx
Labels: 👨‍💻 프론트엔드

#377 F31 - 스켈레톤 UI를 리팩토링한다
  frontend/src/components/CardSkeletonList.tsx
  frontend/src/components/HeaderSkeleton.tsx
  frontend/src/pages/PublicSearchResultLoadable.tsx
Labels: 👨‍💻 프론트엔드

#381 U15 - 프로필 페이지를 스크롤 가능하게 변경한다
  frontend/src/pages/ProfilePage.tsx
Labels: 👨‍💻 프론트엔드

#383 F32 - 필요하지 않은 webpack 설정 및 라이브러리 삭제
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: 👨‍💻 프론트엔드

#386 F33 - 비회원도 검색이 가능하도록 수정하기
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/hooks/usePublicCard.ts
  frontend/src/pages/LogoutPage.tsx
  frontend/src/pages/OAuthCallbackPage.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/WorkbookEditPage.tsx
Labels: 👨‍💻 프론트엔드

#387 B46 - sonarqube 커버리지 기준을 설정한다
  backend/build.gradle
  backend/lombok.config
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/domain/user/UserTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookTest.java
  backend/src/test/java/botobo/core/ui/search/SearchKeywordTest.java
Labels: 👩‍💻 백엔드

#391 F35 - 파비콘 추가 및 og 속성 추가하기
  frontend/public/favicon.png
  frontend/public/index.html
  frontend/public/netlify.toml
  frontend/webpack.common.js
Labels: 👨‍💻 프론트엔드

#395 B47 - tag 최대 개수 5개로 늘린다
  backend/build.gradle
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
  backend/src/test/java/botobo/core/domain/user/UserTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookTest.java
Labels: 👩‍💻 백엔드

#402 F36 - 하트 위치 변경 및 태그 검색 기능 추가
  frontend/src/components/Hashtag.tsx
  frontend/src/components/PublicCardsSelectBox.tsx
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/CardsPage.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
Labels: 👨‍💻 프론트엔드

#404 F35 - 전체 메시지 수정 및 폼 빈값 입력 시 에러 메시지를 나타낸다
  frontend/src/components/CardAddForm.tsx
  frontend/src/components/CardEditForm.tsx
  frontend/src/contexts/FormProvider.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/WorkbookAddPage.tsx
  frontend/src/pages/WorkbookEditPage.tsx
Labels: 👨‍💻 프론트엔드

#406 F37 - api 레이어 정리
  frontend/src/api/card.ts
  frontend/src/api/index.ts
  frontend/src/api/quiz.ts
  frontend/src/api/request.ts
  frontend/src/api/search.ts
  frontend/src/api/user.ts
  frontend/src/api/workbook.ts
Labels: 👨‍💻 프론트엔드

#408 F38 - 문제집 가져가기 기본값 설정을 수정한다
  frontend/src/components/PublicCardsSelectBox.tsx
Labels: 👨‍💻 프론트엔드

#410 UI12 - 로딩 스피너 만들기
  frontend/src/components/LoadingSpinner.tsx
  frontend/src/components/PublicWorkbookList.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/usePublicSearch.ts
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
Labels: 👨‍💻 프론트엔드

#389 F34 - 예외처리를 수정한다
  frontend/src/components/QuizStarter.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useCard.ts
  frontend/src/hooks/useErrorHandler.ts
  frontend/src/hooks/useProfile.ts
  frontend/src/hooks/usePublicCard.ts
  frontend/src/hooks/usePublicSearch.ts
  frontend/src/hooks/useQuizResult.ts
  frontend/src/hooks/useQuizSetting.ts
  frontend/src/hooks/useWorkbook.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/SearchPage.tsx
Labels: 👨‍💻 프론트엔드

#396 B43 - 인수테스트 리팩토링
  backend/src/test/java/botobo/core/acceptance/AcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/DatabaseCleaner.java
  backend/src/test/java/botobo/core/acceptance/DomainAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/admin/AdminAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/card/CardAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/card/QuizAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/search/SearchAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/user/UserAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/utils/Fixture.java
Labels: 👩‍💻 백엔드

#413 UI13 - 반응형 구현하기
  frontend/src/components/CardSkeletonList.tsx
  frontend/src/components/HeaderSkeleton.tsx
  frontend/src/components/MainHeader.tsx
  frontend/src/components/PageHeader.tsx
  frontend/src/components/PublicSearchList.tsx
  frontend/src/components/PublicWorkbookList.tsx
  frontend/src/components/QuizStarter.tsx
  frontend/src/components/WorkbookList.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/responsive.ts
  frontend/src/constants/theme.ts
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/contexts/SnackbarProvider.tsx
  frontend/src/pages/CardsLoadable.tsx
  frontend/src/pages/CardsPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainLoadable.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PageTemplate.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/PublicCardsLoadable.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/PublicSearchResultLoadable.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
  frontend/src/pages/QuizPage.tsx
  frontend/src/pages/QuizResultPage.tsx
  frontend/src/pages/QuizSettingLoadable.tsx
  frontend/src/pages/QuizSettingPage.tsx
  frontend/src/pages/WorkbookAddPage.tsx
  frontend/src/pages/WorkbookEditPage.tsx
  frontend/src/pages/index.ts
  frontend/src/types/emotion.d.ts
Labels: 👨‍💻 프론트엔드

#416 UI14 - 반응형을 구현한다
  frontend/src/components/CardTextArea.tsx
  frontend/src/components/MainHeader.tsx
  frontend/src/components/QuizStarter.tsx
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/contexts/SnackbarProvider.tsx
  frontend/src/hooks/usePublicSearch.ts
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/QuizSettingLoadable.tsx
Labels: 👨‍💻 프론트엔드

#422 Hotfix - release 버전 변경
  frontend/package.json
  frontend/webpack.common.js
Labels: 👨‍💻 프론트엔드

#446 UI15 - 검색 페이지의 문제집, 태그, 작성자 UI를 삭제한다
  frontend/src/pages/PublicSearchPage.tsx
Labels: 👨‍💻 프론트엔드

#447 UI16 - 검색 상세 페이지에서 작성자 순, 태그 순 UI를 추가한다
  frontend/src/assets/rotate-left-circular-arrow-interface-symbol.svg
  frontend/src/components/Button.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
Labels: 👨‍💻 프론트엔드
