Repository woowacourse-teams/2021-botobo, pull requests merged in 2021-07, with the labels that each got.

#49 B09 - 카테고리 조회 시 카드의 개수를 함께 반환하도록 수정한다.
  backend/src/main/java/botobo/core/category/domain/Category.java
  backend/src/main/java/botobo/core/category/dto/CategoryResponse.java
  backend/src/test/java/botobo/core/category/domain/CategoryTest.java
Labels: 👩‍💻 백엔드, 📍 기능

#218 W04 - Workbook을 조회하는 기능을 개선한다.
  backend/src/docs/sql/dml.sql
  backend/src/main/java/botobo/core/admin/dto/AdminWorkbookRequest.java
  backend/src/main/java/botobo/core/quiz/application/QuizService.java
  backend/src/main/java/botobo/core/quiz/application/WorkbookService.java
  backend/src/main/java/botobo/core/quiz/domain/card/CardRepository.java
  backend/src/main/java/botobo/core/quiz/domain/workbook/AccessType.java
  backend/src/main/java/botobo/core/quiz/domain/workbook/OwnerType.java
  backend/src/main/java/botobo/core/quiz/domain/workbook/SearchKeyword.java
  backend/src/main/java/botobo/core/quiz/domain/workbook/Workbook.java
  backend/src/main/java/botobo/core/quiz/domain/workbook/WorkbookCriteria.java
  backend/src/main/java/botobo/core/quiz/domain/workbook/WorkbookFinder.java
  backend/src/main/java/botobo/core/quiz/domain/workbook/WorkbookRepository.java
  backend/src/main/java/botobo/core/quiz/domain/workbook/WorkbookSearchParams.java
  backend/src/main/java/botobo/core/quiz/dto/workbook/WorkbookResponse.java
  backend/src/main/java/botobo/core/quiz/exception/WorkbookSearchFailureException.java
  backend/src/main/java/botobo/core/quiz/ui/WorkbookController.java
  backend/src/main/java/botobo/core/user/domain/User.java
  backend/src/test/java/botobo/core/AcceptanceTest.java
  backend/src/test/java/botobo/core/admin/AdminAcceptanceTest.java
  backend/src/test/java/botobo/core/documentation/AdminDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/CardDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/QuizDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
  backend/src/test/java/botobo/core/quiz/CardAcceptanceTest.java
  backend/src/test/java/botobo/core/quiz/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/quiz/application/QuizServiceTest.java
  backend/src/test/java/botobo/core/quiz/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/quiz/domain/workbook/AccessTypeTest.java
  backend/src/test/java/botobo/core/quiz/domain/workbook/OwnerTypeTest.java
  backend/src/test/java/botobo/core/quiz/domain/workbook/SearchKeywordTest.java
  backend/src/test/java/botobo/core/quiz/domain/workbook/WorkbookCriteriaTest.java
  backend/src/test/java/botobo/core/quiz/domain/workbook/WorkbookFinderTest.java
  backend/src/test/java/botobo/core/quiz/domain/workbook/WorkbookTest.java
  backend/src/test/java/botobo/core/utils/RequestBuilder.java
  backend/src/test/java/botobo/core/utils/TestUtils.java
Labels: backend

#249 W08 - 문제집 추가, 조회, 수정, 삭제 기능에 User를 도입한다.
  backend/src/docs/asciidoc/workbooks.adoc
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/domain/user/User.java
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookRequest.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookResponse.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookUpdateRequest.java
  backend/src/main/java/botobo/core/exception/NotAuthorException.java
  backend/src/main/java/botobo/core/ui/WorkbookController.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/botobo/core/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/utils/RequestBuilder.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/QuizDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/utils/DocumentRequestBuilder.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookRepositoryTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookTest.java
Labels: 👩‍💻 백엔드

#266 B37 - 백엔드 레이블이 붙지 않은 경우 백엔드 젠킨스 빌드를 하지 않는다.
  backend/README.md
  frontend/Jenkinsfile
Labels: 👨‍💻 프론트엔드, 👩‍💻 백엔드

#258 B35 - api 요청을 intelliJ 에서 보낼 수 있도록 http 파일을 만든다.
  backend/src/docs/request/admin.http
  backend/src/docs/request/cards.http
  backend/src/docs/request/login.http
  backend/src/docs/request/quizzes.http
  backend/src/docs/request/users.http
  backend/src/docs/request/workbooks.http
Labels: 👩‍💻 백엔드

#263 B36 - 일반 유저 생성을 DataLoader 에 추가한다.
  backend/src/docs/sql/dml.sql
  backend/src/main/java/botobo/core/DataLoader.java
  backend/src/test/java/botobo/core/domain/card/CardRepositoryTest.java
  backend/src/test/java/botobo/core/domain/user/UserRepositoryTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookRepositoryTest.java
Labels: 👩‍💻 백엔드

#256 C07 - Card CRUD에 유저 추가
  .gitignore
  backend/src/docs/sql/dml.sql
  backend/src/main/java/botobo/core/application/CardService.java
  backend/src/main/java/botobo/core/domain/card/Card.java
  backend/src/main/java/botobo/core/domain/user/AppUser.java
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/main/java/botobo/core/dto/card/CardUpdateRequest.java
  backend/src/main/java/botobo/core/ui/CardController.java
  backend/src/test/java/botobo/core/acceptance/DomainAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/card/CardAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/utils/RequestBuilder.java
  backend/src/test/java/botobo/core/application/CardServiceTest.java
  backend/src/test/java/botobo/core/documentation/CardDocumentationTest.java
  backend/src/test/java/botobo/core/domain/card/CardRepositoryTest.java
  backend/src/test/java/botobo/core/domain/card/CardTest.java
  backend/src/test/java/botobo/core/domain/user/AppUserTest.java
Labels: 👩‍💻 백엔드

#273 fix: 카드 삭제 시 workbook이 널일 때 조건 추가 및 C07 반영 안된 변경사항 추가
  backend/src/main/java/botobo/core/domain/card/Card.java
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/test/java/botobo/core/application/CardServiceTest.java
Labels: 👩‍💻 백엔드

#276 P02 - 바로 풀어보기 기능 및 문제 가져오기 UI를 구현한다
  frontend/babel.config.js
  frontend/jenkinsfiles/frontend-dev
  frontend/package.json
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/assets/chevron-down-solid.svg
  frontend/src/assets/down-arrow.svg
  frontend/src/components/Quiz.tsx
  frontend/src/components/QuizResult.tsx
  frontend/src/components/QuizStarter.tsx
  frontend/src/components/SelectBox.tsx
  frontend/src/components/WorkbookList.tsx
  frontend/src/components/index.ts
  frontend/src/constants/index.ts
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/hooks/usePublicCard.ts
  frontend/src/hooks/useQuiz.ts
  frontend/src/hooks/useQuizSetting.ts
  frontend/src/hooks/useWorkbook.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/QuizPage.tsx
  frontend/src/recoil/quizState.ts
  frontend/src/recoil/workbookState.ts
  frontend/src/styles/index.ts
  frontend/src/styles/scroll.ts
  frontend/src/types/index.ts
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/yarn.lock
Labels: 👨‍💻 프론트엔드, 💄UI, 📍 기능

#278 fix: 스프링 재시작시 로그 파일 제목에 날짜 포함되도록 수정
  backend/src/main/resources/logback/error-file-appender.xml
  backend/src/main/resources/logback/http-file-appender.xml
  backend/src/main/resources/logback/info-file-appender.xml
  backend/src/main/resources/logback/query-file-appender.xml
  backend/src/main/resources/logback/warn-file-appender.xml
Labels: 🐜 버그, 👩‍💻 백엔드

#280 Q15 - 다음에 또 보기 기능을 구현한다
  frontend/src/api/index.ts
  frontend/src/components/Button.tsx
  frontend/src/hooks/useQuizResult.ts
  frontend/src/hooks/useQuizSetting.ts
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/QuizResultPage.tsx
Labels: 👨‍💻 프론트엔드, 📍 기능

#284 P03 - 내 문제집으로 가져가기 기능을 구현한다
  frontend/src/api/index.ts
  frontend/src/components/Confirm.tsx
  frontend/src/components/QnACard.tsx
  frontend/src/components/SelectBox.tsx
  frontend/src/components/WorkbookList.tsx
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/usePublicCard.ts
  frontend/src/hooks/useWorkbook.ts
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/QuizResultPage.tsx
  frontend/src/recoil/index.ts
Labels: 👨‍💻 프론트엔드, 📍 기능

#286 F18 - 전체적인 디자인 리터치
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/components/CardTextArea.tsx
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/hooks/usePublicWorkbook.ts
  frontend/src/pages/MainLoadable.tsx
  frontend/src/pages/PublicCardsLoadable.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicWorkbookPage.tsx
  frontend/src/pages/index.ts
Labels: 👨‍💻 프론트엔드, 💄UI

#267 W09 - 문제집으로 카드 가져가기
  backend/src/docs/request/admin.http
  backend/src/docs/request/login.http
  backend/src/docs/request/quizzes.http
  backend/src/docs/request/workbooks.http
  backend/src/main/java/botobo/core/DataLoader.java
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/botobo/core/domain/card/Card.java
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/main/java/botobo/core/dto/card/ScrapCardRequest.java
  backend/src/main/java/botobo/core/ui/WorkbookController.java
  backend/src/test/java/botobo/core/acceptance/DomainAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/card/CardAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/utils/RequestBuilder.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/application/CardServiceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/DocumentationTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/utils/DocumentRequestBuilder.java
Labels: 👩‍💻 백엔드
