Repository woowacourse-teams/2021-botobo, pull requests merged in 2021-09, with the labels that each got.

#451 S01 - 추천 태그 API 구현
  backend/src/docs/asciidoc/search.adoc
  backend/src/main/java/botobo/core/application/SearchService.java
  backend/src/main/java/botobo/core/domain/tag/TagRepository.java
  backend/src/main/java/botobo/core/ui/search/SearchController.java
  backend/src/main/java/botobo/core/ui/search/SearchRelated.java
  backend/src/main/java/botobo/core/util/SimilarityChecker.java
  backend/src/test/java/botobo/core/acceptance/search/SearchAcceptanceTest.java
  backend/src/test/java/botobo/core/application/SearchServiceTest.java
  backend/src/test/java/botobo/core/documentation/SearchDocumentationTest.java
  backend/src/test/java/botobo/core/domain/tag/TagRepositoryTest.java
  backend/src/test/java/botobo/core/util/SimilarityCheckerTest.java
Labels: 👩‍💻 백엔드

#455 fix/S01: SearchRelated 테스트 추가
  backend/src/main/java/botobo/core/util/SimilarityChecker.java
  backend/src/test/java/botobo/core/ui/search/SearchRelatedTest.java
Labels: 👩‍💻 백엔드

#448 W01 - 다양한 문제집 보러가기 API 구현
  backend/src/docs/asciidoc/workbooks.adoc
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/botobo/core/domain/workbook/WorkbookRepository.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookResponse.java
  backend/src/main/java/botobo/core/ui/WorkbookController.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logback/query-file-dev-appender.xml
  backend/src/main/resources/logback/query-file-prod-appender.xml
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookRepositoryTest.java
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/api/search.ts
  frontend/src/api/workbook.ts
  frontend/src/hooks/usePublicSearch.ts
  frontend/src/pages/PublicSearchLoadable.tsx
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/index.ts
  frontend/src/recoil/index.ts
  frontend/src/recoil/workbookState.ts
Labels: 👩‍💻 백엔드

#453 S04 - 검색 페이지에서 초기 문제집 100개를 보여준다
  frontend/src/hooks/useCard.ts
  frontend/src/hooks/usePublicCard.ts
  frontend/src/hooks/usePublicSearch.ts
  frontend/src/pages/PublicSearchPage.tsx
Labels: 👨‍💻 프론트엔드

#454 UI17 - 검색 상세 페이지에서 바텀 모달을 추가한다(태그, 작성자 필터링)
  frontend/src/assets/tick.svg
  frontend/src/components/MultiFilterSelector.tsx
  frontend/src/components/index.ts
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/pages/PublicSearchResultLoadable.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
  frontend/src/pages/QuizPage.tsx
  frontend/src/types/filter.ts
  frontend/src/utils/index.ts
  frontend/src/utils/mobile.ts
Labels: 👨‍💻 프론트엔드

#457 S05 - 검색 페이지에서 추천 검색어 기능을 구현한다
  frontend/src/contexts/FormProvider.tsx
  frontend/src/hooks/useErrorHandler.ts
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/ProfilePage.tsx
  frontend/src/pages/PublicSearchPage.tsx
Labels: 👨‍💻 프론트엔드

#458 F40 - Guide 페이지를 수정한다
  frontend/src/pages/Guide.tsx
Labels: 👨‍💻 프론트엔드

#456 T01- (필터) 검색어에 해당하는 문제집에 등록된 모든 태그를 가져온다.
  backend/src/docs/asciidoc/tags.adoc
  backend/src/main/java/botobo/core/application/AdminService.java
  backend/src/main/java/botobo/core/application/SearchService.java
  backend/src/main/java/botobo/core/application/TagService.java
  backend/src/main/java/botobo/core/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/botobo/core/domain/card/Card.java
  backend/src/main/java/botobo/core/domain/tag/Tag.java
  backend/src/main/java/botobo/core/domain/tag/TagRepository.java
  backend/src/main/java/botobo/core/domain/tag/Tags.java
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/main/java/botobo/core/dto/admin/AdminWorkbookRequest.java
  backend/src/main/java/botobo/core/dto/tag/FilterCriteria.java
  backend/src/main/java/botobo/core/exception/common/ErrorType.java
  backend/src/main/java/botobo/core/exception/workbook/WorkbookNameBlankException.java
  backend/src/main/java/botobo/core/ui/TagController.java
  backend/src/main/java/botobo/core/ui/search/SearchKeyword.java
  backend/src/test/java/botobo/core/TestUtils.java
  backend/src/test/java/botobo/core/acceptance/card/QuizAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/tag/TagAcceptanceTest.java
  backend/src/test/java/botobo/core/application/TagServiceTest.java
  backend/src/test/java/botobo/core/documentation/TagDocumentationTest.java
  backend/src/test/java/botobo/core/domain/tag/TagRepositoryTest.java
  backend/src/test/java/botobo/core/domain/tag/TagsTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookTest.java
  backend/src/test/java/botobo/core/dto/tag/FilterCriteriaTest.java
  backend/src/test/java/botobo/core/utils/Fixture.java
Labels: 👩‍💻 백엔드

#463 U01 - (필터) 검색어에 해당하는 문제집의 작성자를 모두 가져온다.
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/users.adoc
  backend/src/main/java/botobo/core/application/AdminService.java
  backend/src/main/java/botobo/core/application/TagService.java
  backend/src/main/java/botobo/core/application/UserService.java
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/botobo/core/domain/tag/TagRepository.java
  backend/src/main/java/botobo/core/domain/user/UserRepository.java
  backend/src/main/java/botobo/core/domain/workbook/Workbook.java
  backend/src/main/java/botobo/core/dto/user/UserFilterResponse.java
  backend/src/main/java/botobo/core/ui/TagController.java
  backend/src/main/java/botobo/core/ui/UserController.java
  backend/src/test/java/botobo/core/acceptance/DomainAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/card/QuizAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/tag/TagAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/user/UserAcceptanceTest.java
  backend/src/test/java/botobo/core/application/TagServiceTest.java
  backend/src/test/java/botobo/core/application/UserServiceTest.java
  backend/src/test/java/botobo/core/documentation/TagDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/UserDocumentationTest.java
  backend/src/test/java/botobo/core/domain/tag/TagRepositoryTest.java
  backend/src/test/java/botobo/core/domain/user/UserRepositoryTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookRepositoryTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookTest.java
  backend/src/test/java/botobo/core/utils/Fixture.java
Labels: 👩‍💻 백엔드

#460 S06 - 검색 상세 페이지에서 작성자, 태그 순 필터링 검색 기능을 구현한다.
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/api/index.ts
  frontend/src/api/search.ts
  frontend/src/api/workbook.ts
  frontend/src/components/MultiFilterSelector.tsx
  frontend/src/components/PublicSearchList.tsx
  frontend/src/components/PublicWorkbookList.tsx
  frontend/src/components/index.ts
  frontend/src/constants/index.ts
  frontend/src/constants/search.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/usePublicSearch.ts
  frontend/src/hooks/usePublicSearchQuery.ts
  frontend/src/hooks/usePublicSearchResult.ts
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
  frontend/src/recoil/index.ts
  frontend/src/recoil/searchState.ts
  frontend/src/recoil/workbookState.ts
  frontend/src/types/filter.ts
  frontend/src/types/index.ts
Labels: 👨‍💻 프론트엔드

#470 S07 - 자동완성 오류를 수정한다
  frontend/src/pages/PublicSearchPage.tsx
Labels: 👨‍💻 프론트엔드

#464 S02 - 변경된 검색 API에 맞게 기능 구현한다.
  backend/build.gradle
  backend/src/docs/asciidoc/admin.adoc
  backend/src/docs/asciidoc/quizzes.adoc
  backend/src/docs/asciidoc/search.adoc
  backend/src/main/java/botobo/core/application/SearchService.java
  backend/src/main/java/botobo/core/config/QuerydslConfig.java
  backend/src/main/java/botobo/core/domain/workbook/WorkbookRepository.java
  backend/src/main/java/botobo/core/domain/workbook/WorkbookSearchRepository.java
  backend/src/main/java/botobo/core/ui/search/SearchArgumentResolver.java
  backend/src/main/java/botobo/core/ui/search/SearchController.java
  backend/src/main/java/botobo/core/ui/search/SearchCriteria.java
  backend/src/main/java/botobo/core/ui/search/SearchOrder.java
  backend/src/main/java/botobo/core/ui/search/SearchType.java
  backend/src/main/java/botobo/core/ui/search/WorkbookSearchParameter.java
  backend/src/test/java/botobo/core/acceptance/search/SearchAcceptanceTest.java
  backend/src/test/java/botobo/core/application/WorkbookServiceTest.java
  backend/src/test/java/botobo/core/documentation/SearchDocumentationTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookSearchRepositoryTest.java
  backend/src/test/java/botobo/core/ui/search/SearchOrderTest.java
  backend/src/test/java/botobo/core/ui/search/SearchTypeTest.java
  backend/src/test/java/botobo/core/ui/search/WorkbookSearchParameterTest.java
Labels: 👩‍💻 백엔드

#475 B04 - health check 위한 api를 생성한다
  backend/src/main/java/botobo/core/ui/InfraController.java
Labels: 👩‍💻 백엔드

#476 B04 - fix: health check 위한 api 토큰 없이 사용하도록 변경
  backend/src/main/java/botobo/core/config/AuthenticationPrincipalConfig.java
Labels: 👩‍💻 백엔드

#477 B04 - fix: jar 빌드시 올바른 설정파일 서브모듈로부터 복사
  .gitignore
  backend/build.gradle
Labels: 👩‍💻 백엔드

#472 S08 - 문제집 검색 시 초기화가 되지 않는 버그 수정
  frontend/src/components/PublicWorkbookList.tsx
  frontend/src/hooks/usePublicSearchResult.ts
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
Labels: 👨‍💻 프론트엔드

#490 C13 - publicCards페이지에 Id 넣기
  frontend/src/Router.tsx
  frontend/src/components/PublicWorkbookList.tsx
  frontend/src/hooks/usePublicCard.ts
  frontend/src/hooks/useRouter.ts
  frontend/src/pages/PublicSearchPage.tsx
Labels: 👨‍💻 프론트엔드

#491 S09 - 검색 창 랜덤 데이터 캐싱
  frontend/src/components/QuizStarter.tsx
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/recoil/workbookState.ts
Labels: 👨‍💻 프론트엔드

#494 B04 - fix: 로깅 설정 복구
  backend/src/main/resources/logback-spring.xml
Labels: 👩‍💻 백엔드

#496 W02 - 다양한 문제집 api 응답에 heartCount와 tags를 추가한다.
  backend/src/main/java/botobo/core/application/WorkbookService.java
  backend/src/main/java/botobo/core/dto/workbook/WorkbookResponse.java
  backend/src/test/java/botobo/core/documentation/SearchDocumentationTest.java
  backend/src/test/java/botobo/core/documentation/WorkbookDocumentationTest.java
Labels: 👩‍💻 백엔드

#498 F45 - 코드 스플리팅
  frontend/src/Router.tsx
  frontend/src/pages/index.ts
  frontend/webpack.common.js
Labels: 👨‍💻 프론트엔드

#508 etc: 주석 삭제, config.datasource 자코코에서 제외
  backend/build.gradle
  backend/src/main/java/botobo/core/config/datasource/RoutingDataSource.java
Labels: 👩‍💻 백엔드, 🐜 버그

#511 fix: EntityManagerFactory 빈 생성하는 부분 변경
  backend/src/main/java/botobo/core/config/datasource/DataSourceConfig.java
Labels: 👩‍💻 백엔드

#512 fix: EntityManagerFactoryBuilder 를 새로 생성하도록 변경, HibernateJpaVendorAda…
  backend/src/main/java/botobo/core/config/datasource/DataSourceConfig.java
Labels: 👩‍💻 백엔드

#513 fix: DataSourceConfig @Profile 변경
  backend/src/main/java/botobo/core/config/datasource/DataSourceConfig.java
Labels: 👩‍💻 백엔드

#500 F44 - 전체적인 UI 개선
  frontend/src/components/PublicQnACard.tsx
  frontend/src/components/QnACard.tsx
  frontend/src/components/Quiz.tsx
  frontend/src/components/QuizResult.tsx
Labels: 👨‍💻 프론트엔드

#504 C15 - Cards페이지에 Id 넣기
  frontend/src/Router.tsx
  frontend/src/components/CardTemplate.tsx
  frontend/src/components/MainHeader.tsx
  frontend/src/components/PublicWorkbook.tsx
  frontend/src/components/PublicWorkbookList.tsx
  frontend/src/components/Workbook.tsx
  frontend/src/components/WorkbookList.tsx
  frontend/src/components/index.ts
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/route.ts
  frontend/src/constants/storage.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useCard.ts
  frontend/src/hooks/useErrorHandler.ts
  frontend/src/hooks/useLogout.ts
  frontend/src/hooks/usePublicCard.ts
  frontend/src/hooks/usePublicSearchResult.ts
  frontend/src/hooks/useRouter.ts
  frontend/src/hooks/useWorkbook.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
  frontend/src/pages/QuizSettingPage.tsx
  frontend/src/pages/WorkbookEditPage.tsx
  frontend/src/recoil/index.ts
  frontend/src/recoil/workbookState.ts
  frontend/src/types/idParam.ts
Labels: 👨‍💻 프론트엔드

#507 다양한 문제집 보러가기 0개 문제집 제외하기
  backend/src/main/java/botobo/core/domain/workbook/WorkbookRepository.java
  backend/src/test/java/botobo/core/acceptance/DomainAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/search/SearchAcceptanceTest.java
  backend/src/test/java/botobo/core/acceptance/workbook/WorkbookAcceptanceTest.java
  backend/src/test/java/botobo/core/domain/workbook/WorkbookRepositoryTest.java
Labels: 👩‍💻 백엔드

#517 C14 - 카드 상세 페이지에서 태그를 눌렀을 때 태그 검색되는 기능 구현
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicSearchResultPage.tsx
Labels: 👨‍💻 프론트엔드

#499 P05 - 공유 문제집에 태그, 좋아요를 보여준다
  frontend/src/components/Checkbox.tsx
  frontend/src/components/PublicWorkbook.tsx
  frontend/src/components/PublicWorkbookList.tsx
  frontend/src/components/SelectBox.tsx
  frontend/src/components/Workbook.tsx
  frontend/src/pages/PublicCardsPage.tsx
  frontend/src/pages/PublicSearchLoadable.tsx
  frontend/src/pages/PublicSearchPage.tsx
  frontend/src/pages/PublicSearchResultLoadable.tsx
Labels: 👨‍💻 프론트엔드

#518 F46 - Webpack chunk 분리, font preload
  frontend/package.json
  frontend/public/index.html
  frontend/webpack.prod.js
Labels: 👨‍💻 프론트엔드

#535 B08 - DataSourceConfig 수정
  backend/src/main/java/botobo/core/config/datasource/DataSourceConfig.java
Labels: 👩‍💻 백엔드, 🛠 리팩터링
